clickhouse_ops:
  target: dev
  outputs:
    dev:
      type: clickhouse
      user: default
      password: phlo_oxAe3UfHXuA5jg_1uelYiFoIuJPPuOYEle8Nneno__A
      host: clickhouse
      port: 8123
      schema: marts
      threads: 2
