"""Registers the Phlo API service plugin.

The plugin class is generated by ``service_plugin_class`` and carries
identity metadata only; all behavior lives in the phlo-api package itself.
Loaded through the phlo plugin entry-point mechanism at startup rather than imported directly.
Registers the phlo-api service through the phlo.plugins service plugin factory.
"""

from __future__ import annotations

from phlo.plugins import service_plugin_class


PhloApiServicePlugin = service_plugin_class(
    "PhloApiServicePlugin",
    name="phlo-api",
    version="0.1.0",
    description="Backend API exposing Phlo internals to Observatory",
    author="Phlo Team",
    tags=["api", "observability"],
)
