"""Authoritative security classification for API entry points.

The manifest is deliberately kept beside the API package rather than spread
across route decorators.  Every route that FastAPI exposes must have one
classification, and protected classifications always resolve a concrete
resource before the handler is called.
"""

from __future__ import annotations

import json
import os
from uuid import uuid4
from dataclasses import dataclass, replace
from typing import Any, Iterable, NoReturn

from fastapi import HTTPException, Request
from starlette.routing import Match
from starlette.responses import JSONResponse

from phlo.capabilities import DecisionContext, ResourceRef
from phlo.logging import bind_context, clear_context, get_logger
from phlo.rbac.models import CanonicalAction
from phlo.security import enforce, is_regulated
from phlo.security.mode import requires_http_authorization
from phlo.infrastructure.config import get_api_authorization_config

from phlo_api.api.authentication import get_request_principal
from phlo_api.api.authorization import (
    create_decision_context,
    get_request_correlation_id,
    get_authorization_backend,
    resolve_request_principal,
)


@dataclass(frozen=True)
class OperationSpec:
    """Security classification for one externally reachable operation."""

    operation_name: str
    surface: str
    action: str
    resource_type: str
    public: bool = False
    resource_keys: tuple[str, ...] = ()
    resource_sources: tuple[tuple[str, str], ...] = ()
    methods: tuple[str, ...] = ()
    path: str | None = None
    endpoint: str | None = None


HTTP_ROUTE_KEY_MANIFEST: dict[tuple[str, str], OperationSpec] = {}
logger = get_logger(__name__)
RUN_REPORT_RESOURCE_ID_ATTRIBUTE = "phlo.run_report_resource_id"

_AUTHORIZATION_MODE_ENV = "PHLO_AUTHORIZATION_MODE"
_AUTHORIZATION_MODE_OPTIONAL = "optional"
_AUTHORIZATION_MODE_REQUIRED = "required"


def _specs(
    names: Iterable[str],
    *,
    action: str,
    resource_type: str,
    resource_keys: tuple[str, ...] = (),
    resource_sources: tuple[tuple[str, str], ...] = (),
) -> tuple[OperationSpec, ...]:
    return tuple(
        OperationSpec(
            operation_name=name,
            surface="http",
            action=action,
            resource_type=resource_type,
            resource_keys=resource_keys,
            resource_sources=resource_sources,
        )
        for name in names
    )


# This is the only route-name-to-policy mapping in phlo-api.  The startup
# validator compares it with the actual FastAPI route table, including docs
# routes generated by FastAPI itself.
HTTP_ROUTE_DECLARATIONS: tuple[OperationSpec, ...] = (
    OperationSpec(
        operation_name="health",
        surface="http",
        action=CanonicalAction.OBSERVABILITY_READ.value,
        resource_type="observability",
        public=True,
    ),
    *_specs(
        (
            "openapi",
            "swagger_ui_html",
            "swagger_ui_redirect",
            "redoc_html",
            "get_config",
            "get_plugins",
            "get_registry",
            "get_api_backends",
            "get_contracts",
            "list_templates",
            "list_workflows",
            "run_doctor",
        ),
        action=CanonicalAction.PLATFORM_METADATA_READ.value,
        resource_type="platform_metadata",
    ),
    *_specs(
        ("get_plugins_by_type",),
        action=CanonicalAction.PLATFORM_METADATA_READ.value,
        resource_type="platform_metadata",
        resource_keys=("plugin_type",),
    ),
    *_specs(
        ("get_plugin_info",),
        action=CanonicalAction.PLATFORM_METADATA_READ.value,
        resource_type="platform_metadata",
        resource_keys=("plugin_type", "name"),
    ),
    *_specs(
        ("get_api_backend_info",),
        action=CanonicalAction.PLATFORM_METADATA_READ.value,
        resource_type="platform_metadata",
        resource_keys=("name",),
    ),
    *_specs(
        ("get_contract",),
        action=CanonicalAction.PLATFORM_METADATA_READ.value,
        resource_type="platform_metadata",
        resource_keys=("table_name",),
    ),
    *_specs(
        ("create_workflow", "validate_workflow", "validate_schema", "lint_project"),
        action=CanonicalAction.OBJECT_WRITE.value,
        resource_type="project",
    ),
    *_specs(
        ("get_services",),
        action=CanonicalAction.SERVICE_READ.value,
        resource_type="service",
    ),
    *_specs(
        ("get_service_info",),
        action=CanonicalAction.SERVICE_READ.value,
        resource_type="service",
        resource_keys=("name",),
    ),
    *_specs(
        ("get_maintenance_status", "get_maintenance_metrics"),
        action=CanonicalAction.MAINTENANCE_READ.value,
        resource_type="maintenance",
    ),
    *_specs(
        (
            "get_health_summary",
            "get_service_status",
            "get_platform_metrics",
            "get_recent_alerts",
            "get_dashboard_links",
            "get_logs_query_link",
            "get_metrics_query_link",
        ),
        action=CanonicalAction.OBSERVABILITY_READ.value,
        resource_type="observability",
    ),
    *_specs(
        ("get_run_trace_spans",),
        action=CanonicalAction.OBSERVABILITY_READ.value,
        resource_type="observability",
        resource_keys=("run_id",),
    ),
    *_specs(
        ("get_trace_spans",),
        action=CanonicalAction.OBSERVABILITY_READ.value,
        resource_type="observability",
    ),
    *_specs(
        ("query_logs",),
        action=CanonicalAction.AUDIT_READ.value,
        resource_type="audit",
    ),
    *_specs(
        ("query_run_logs", "stream_run_logs"),
        action=CanonicalAction.AUDIT_READ.value,
        resource_type="audit",
        resource_keys=("run_id",),
    ),
    *_specs(
        ("query_asset_logs",),
        action=CanonicalAction.AUDIT_READ.value,
        resource_type="audit",
        resource_keys=("asset_key",),
    ),
    *_specs(
        ("get_log_labels", "get_observatory_logs", "get_observatory_log_facets"),
        action=CanonicalAction.AUDIT_READ.value,
        resource_type="audit",
    ),
    *_specs(
        ("check_connection",),
        action=CanonicalAction.OBSERVABILITY_READ.value,
        resource_type="observability",
    ),
    *_specs(
        (
            "get_observatory_overview",
            "get_observatory_capabilities",
            "get_observatory_surface_capabilities",
            "get_observatory_capability_inventory",
            "get_observatory_services",
            "get_observatory_operations",
            "get_observatory_storage",
            "get_observatory_observability",
            "get_observatory_governance",
            "get_observatory_apis",
            "get_observatory_bi",
            "get_observatory_search",
            "get_observatory_extensions",
            "get_observatory_extension_manifests",
            "get_observatory_workflow_wizard",
        ),
        action=CanonicalAction.ADMIN_READ.value,
        resource_type="admin",
    ),
    *_specs(
        ("get_observatory_service_detail",),
        action=CanonicalAction.ADMIN_READ.value,
        resource_type="admin",
        resource_keys=("service_id",),
    ),
    *_specs(
        ("get_observatory_operation_agent_context", "get_observatory_operation_detail"),
        action=CanonicalAction.ADMIN_READ.value,
        resource_type="admin",
        resource_keys=("operation_id",),
    ),
    *_specs(
        ("get_observatory_extension_asset",),
        action=CanonicalAction.ADMIN_READ.value,
        resource_type="admin",
        resource_keys=("name", "asset_path"),
    ),
    *_specs(
        ("get_observatory_extension_detail",),
        action=CanonicalAction.ADMIN_READ.value,
        resource_type="admin",
        resource_keys=("extension_id",),
    ),
    *_specs(
        ("get_observatory_preferences", "get_observatory_settings"),
        action=CanonicalAction.SETTINGS_READ.value,
        resource_type="settings",
    ),
    *_specs(
        ("get_observatory_dataset_workflow_config",),
        action=CanonicalAction.SETTINGS_READ.value,
        resource_type="settings",
    ),
    *_specs(
        ("get_observatory_runs",),
        action=CanonicalAction.RUN_READ.value,
        resource_type="run",
    ),
    *_specs(
        ("get_observatory_run_status",),
        action=CanonicalAction.RUN_READ.value,
        resource_type="run",
        resource_keys=("run_id",),
    ),
    *_specs(
        ("get_observatory_run_report",),
        action=CanonicalAction.RUN_READ.value,
        resource_type="run",
        resource_keys=("project_id", "run_id", "attempt"),
    ),
    *_specs(
        ("post_observatory_run_retry", "post_observatory_run_cancel"),
        action=CanonicalAction.RUN_MANAGE.value,
        resource_type="run",
        resource_keys=("run_id",),
    ),
    *_specs(
        ("get_observatory_assets",),
        action=CanonicalAction.ASSET_READ.value,
        resource_type="asset",
    ),
    *_specs(
        ("get_observatory_asset_graph",),
        action=CanonicalAction.ASSET_READ.value,
        resource_type="asset",
    ),
    *_specs(
        ("get_observatory_asset_neighbors", "get_observatory_asset_impact"),
        action=CanonicalAction.ASSET_READ.value,
        resource_type="asset",
        resource_keys=("asset_key",),
    ),
    *_specs(
        (
            "get_observatory_asset_materializations",
            "get_observatory_asset_partitions",
            "get_observatory_asset_detail",
        ),
        action=CanonicalAction.ASSET_READ.value,
        resource_type="asset",
        resource_keys=("asset_id",),
    ),
    *_specs(
        ("post_observatory_asset_materialize", "post_observatory_asset_backfill"),
        action=CanonicalAction.ASSET_EXECUTE.value,
        resource_type="asset",
        resource_keys=("asset_id",),
        resource_sources=(("asset_id", "path_body"),),
    ),
    *_specs(
        (
            "get_observatory_datasets",
            "get_observatory_publishing_readiness",
            "get_observatory_tables",
            "get_observatory_pipelines",
        ),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
    ),
    *_specs(
        ("get_observatory_dataset_profile",),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
        resource_keys=("dataset_id",),
    ),
    *_specs(
        ("get_observatory_table_preview",),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
        resource_keys=("table_id",),
    ),
    *_specs(
        ("post_observatory_schema_diff",),
        action=CanonicalAction.ASSET_READ.value,
        resource_type="asset",
        resource_keys=("asset_key",),
        resource_sources=(("asset_key", "body"),),
    ),
    *_specs(
        ("get_observatory_quality",),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
    ),
    *_specs(
        ("get_observatory_stage_diff",),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
        resource_keys=("source_table_id", "target_table_id"),
    ),
    *_specs(
        ("get_observatory_row_journey",),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
        resource_keys=("table_id", "row_id"),
    ),
    *_specs(
        ("get_observatory_quality_detail",),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
        resource_keys=("check_id",),
    ),
    *_specs(
        ("post_observatory_query",),
        action=CanonicalAction.DATASET_QUERY.value,
        # The request carries arbitrary SQL and its Pydantic model does not
        # bind client IDs to that SQL. Dataset grants cannot safely authorize
        # this endpoint, so it is explicitly project-scoped.
        resource_type="project",
    ),
    *_specs(
        (
            "post_observatory_contributing_rows_query",
            "post_observatory_contributing_rows_page",
        ),
        action=CanonicalAction.DATASET_QUERY.value,
        resource_type="dataset",
        resource_keys=("upstream_asset_key", "downstream_asset_key"),
        resource_sources=(
            ("upstream_asset_key", "body"),
            ("downstream_asset_key", "body"),
        ),
    ),
    *_specs(
        ("get_observatory_saved_queries",),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
    ),
    *_specs(
        ("post_observatory_saved_query",),
        action=CanonicalAction.OBJECT_WRITE.value,
        resource_type="project",
    ),
    *_specs(
        ("get_observatory_branches",),
        action=CanonicalAction.CATALOG_READ.value,
        resource_type="catalog",
    ),
    *_specs(
        ("get_observatory_branch_detail",),
        action=CanonicalAction.CATALOG_READ.value,
        resource_type="catalog",
        resource_keys=("branch_name",),
    ),
    *_specs(
        ("post_observatory_branch_action",),
        action=CanonicalAction.CATALOG_MANAGE.value,
        resource_type="catalog",
        resource_keys=("branch_name", "target"),
    ),
    *_specs(
        ("get_observatory_extension_settings",),
        action=CanonicalAction.SETTINGS_READ.value,
        resource_type="settings",
        resource_keys=("name",),
    ),
    *_specs(
        ("put_observatory_preferences",),
        action=CanonicalAction.SETTINGS_MANAGE.value,
        resource_type="settings",
    ),
    *_specs(
        ("put_observatory_extension_settings",),
        action=CanonicalAction.SETTINGS_MANAGE.value,
        resource_type="settings",
        resource_keys=("name",),
    ),
    *_specs(
        ("put_observatory_dataset_workflow_config",),
        action=CanonicalAction.SETTINGS_MANAGE.value,
        resource_type="settings",
    ),
    *_specs(
        ("post_observatory_workflow_wizard_proposal",),
        action=CanonicalAction.OBJECT_WRITE.value,
        resource_type="object",
    ),
    *_specs(
        ("post_observatory_workflow_wizard_action",),
        action=CanonicalAction.OBJECT_WRITE.value,
        resource_type="object",
        resource_keys=("proposal_id", "action_id"),
        resource_sources=(("proposal_id", "body"), ("action_id", "body")),
    ),
    *_specs(
        ("post_observatory_action",),
        action=CanonicalAction.SERVICE_MANAGE.value,
        resource_type="service",
        resource_keys=("service_id", "action_id", "name", "package"),
        resource_sources=(
            ("service_id", "body"),
            ("action_id", "body"),
            ("name", "body"),
            ("package", "body"),
        ),
    ),
    *_specs(
        ("post_observatory_package_install",),
        action=CanonicalAction.ADMIN_MANAGE.value,
        resource_type="package",
        resource_keys=("package_name",),
        resource_sources=(("package_name", "body"),),
    ),
)


def _build_http_manifest(declarations: tuple[OperationSpec, ...]) -> dict[str, OperationSpec]:
    """Index ordered declarations while rejecting duplicates before indexing."""
    manifest: dict[str, OperationSpec] = {}
    for spec in declarations:
        if spec.operation_name in manifest:
            raise RuntimeError(f"Duplicate HTTP security manifest operation: {spec.operation_name}")
        manifest[spec.operation_name] = spec
    return manifest


HTTP_ROUTE_MANIFEST = _build_http_manifest(HTTP_ROUTE_DECLARATIONS)

PUBLIC_HTTP_PATHS = frozenset({"/health"})


def _all_manifest_names() -> list[str]:
    return list(HTTP_ROUTE_MANIFEST)


def _http_routes(routes: Iterable[Any], prefix: str = "") -> list[tuple[str, str, Any, str]]:
    """Flatten eager and lazy FastAPI router inclusions for boundary checks."""
    resolved: list[tuple[str, str, Any, str]] = []
    for route in routes:
        included_router = getattr(route, "original_router", None)
        include_context = getattr(route, "include_context", None)
        include_prefix = getattr(include_context, "prefix", None)
        if included_router is not None and isinstance(include_prefix, str):
            resolved.extend(
                _http_routes(getattr(included_router, "routes", ()), prefix + include_prefix)
            )
            continue

        methods = getattr(route, "methods", None)
        path = getattr(route, "path", None)
        name = getattr(route, "name", None)
        if methods and path and name:
            resolved.append((name, prefix + path, route, prefix))
    return resolved


def validate_manifest(app: Any) -> tuple[OperationSpec, ...]:
    """Validate the complete HTTP route table and return resolved entries."""
    duplicate_names = [
        name for name in _all_manifest_names() if _all_manifest_names().count(name) > 1
    ]
    if duplicate_names:
        raise RuntimeError(
            f"Duplicate security manifest operations: {sorted(set(duplicate_names))}"
        )

    actual_routes = _http_routes(app.routes)

    actual_name_counts: dict[str, int] = {}
    for name, _path, _route, _prefix in actual_routes:
        actual_name_counts[name] = actual_name_counts.get(name, 0) + 1
    duplicate_route_names = sorted(name for name, count in actual_name_counts.items() if count > 1)
    if duplicate_route_names:
        raise RuntimeError(
            f"Duplicate HTTP route names in security manifest: {duplicate_route_names!r}"
        )
    manifest_names = set(HTTP_ROUTE_MANIFEST)
    missing = sorted(set(actual_name_counts) - manifest_names)
    stale = sorted(manifest_names - set(actual_name_counts))
    if missing or stale:
        raise RuntimeError(
            f"HTTP security manifest drift: unclassified={missing!r}, stale={stale!r}"
        )

    seen_routes: set[tuple[str, str]] = set()
    route_key_manifest: dict[tuple[str, str], OperationSpec] = {}
    resolved: list[OperationSpec] = []
    for name, path, route, _prefix in actual_routes:
        spec = HTTP_ROUTE_MANIFEST[name]
        for method in sorted(route.methods):
            key = (method, path)
            if key in seen_routes:
                raise RuntimeError(
                    f"Duplicate HTTP security manifest operation for {method} {path}"
                )
            seen_routes.add(key)
            resolved_spec = replace(
                spec,
                methods=tuple(sorted(route.methods)),
                path=path,
            )
            route_key_manifest[key] = resolved_spec
            resolved.append(resolved_spec)

        if path in PUBLIC_HTTP_PATHS and not spec.public:
            # Health is the only intentionally anonymous route.  Keeping this
            # check explicit prevents a later route rename from widening it.
            if name != "health":
                raise RuntimeError(f"Unexpected public HTTP path in manifest: {path}")
        if spec.public and path not in PUBLIC_HTTP_PATHS:
            raise RuntimeError(f"Protected route incorrectly marked public: {path}")

    HTTP_ROUTE_KEY_MANIFEST.clear()
    HTTP_ROUTE_KEY_MANIFEST.update(route_key_manifest)
    return tuple(resolved)


def _route_for_request(app: Any, request: Request) -> tuple[OperationSpec, dict[str, str]] | None:
    for _name, path, route, prefix in _http_routes(app.routes):
        methods = getattr(route, "methods", None)
        if not methods or request.method not in methods:
            continue
        scope = request.scope
        # Routes match against their unprefixed path; strip the accumulated
        # include prefix so FastAPI's matcher sees the registered form while
        # the manifest lookup below still uses the fully prefixed path.
        if prefix:
            request_path = scope.get("path", "")
            if not request_path.startswith(prefix):
                continue
            scope = {**scope, "path": request_path[len(prefix) :] or "/"}
        match, child_scope = route.matches(scope)
        if match is Match.FULL:
            spec = HTTP_ROUTE_KEY_MANIFEST.get((request.method, path))
            if spec is None:
                return None
            return spec, child_scope.get("path_params", {})
    return None


async def _request_json(request: Request) -> Any:
    override = getattr(request.state, "_phlo_security_body_override", None)
    if override is not None:
        return override
    if request.headers.get("content-type", "").split(";", 1)[0].strip().lower() not in {
        "application/json",
        "application/graphql+json",
    }:
        return None
    # Cache the parsed body back onto request._body: Starlette does not buffer
    # stream reads and the route handler still needs the raw body afterwards.
    try:
        content_length = request.headers.get("content-length")
        if content_length and content_length.isdigit() and int(content_length) > 1_048_576:
            raise HTTPException(status_code=413, detail={"error": "request_too_large"})
        chunks: list[bytes] = []
        size = 0
        async for chunk in request.stream():
            size += len(chunk)
            if size > 1_048_576:
                raise HTTPException(status_code=413, detail={"error": "request_too_large"})
            chunks.append(chunk)
        raw = b"".join(chunks)
        request._body = raw
        return json.loads(raw) if raw else None
    except HTTPException:
        raise
    except (UnicodeDecodeError, json.JSONDecodeError):
        return None


async def resolve_resource(
    request: Request,
    spec: OperationSpec,
    path_params: dict[str, str],
) -> ResourceRef:
    """Build the resource reference from the spec's declared resource keys.

    Each key resolves from path, query, or body according to its declared
    source. Conflicting values across sources raise 400 (ambiguous_resource)
    instead of silently preferring one; a body-keyed operation with no
    resolvable key raises 400 (missing_resource).
    """
    sources = dict(spec.resource_sources)
    body_keys = {key for key in spec.resource_keys if sources.get(key) in {"body", "path_body"}}
    body = await _request_json(request) if body_keys else None
    if body is not None and not isinstance(body, dict):
        body = None

    values: list[str] = []
    for key in spec.resource_keys:
        source = sources.get(key, "path_query_body")
        path_value = path_params.get(key)
        query_value = request.query_params.get(key)
        body_value = body.get(key) if isinstance(body, dict) else None
        if source == "body":
            if path_value is not None or query_value is not None:
                raise HTTPException(status_code=400, detail={"error": "ambiguous_resource"})
            selected = body_value
        elif source == "path_body":
            selected = path_value
            if body_value is not None and str(body_value) != str(path_value):
                raise HTTPException(status_code=400, detail={"error": "ambiguous_resource"})
        elif source == "query":
            selected = query_value
        elif source == "path":
            selected = path_value
        else:
            selected = path_value or query_value or body_value
            authoritative = path_value or query_value
            if (
                authoritative is not None
                and body_value is not None
                and str(body_value) != str(authoritative)
            ):
                raise HTTPException(status_code=400, detail={"error": "ambiguous_resource"})
        if selected is not None and str(selected):
            values.append(f"{key}={selected}")

    resource_id = "|".join(values) or None
    if body_keys and not values:
        raise HTTPException(status_code=400, detail={"error": "missing_resource"})
    return ResourceRef(
        resource_type=spec.resource_type,
        resource_id=resource_id or os.environ.get("PHLO_PROJECT_NAME", "project"),
        attributes={"project": os.environ.get("PHLO_PROJECT_NAME", "project")},
    )


def _raise_unauthorized() -> NoReturn:
    raise HTTPException(
        status_code=401,
        detail={"error": "unauthorized", "reason": "authentication_required"},
        headers={"WWW-Authenticate": "Bearer"},
    )


def _enforce_scoped_run_report_service_identity(
    principal: Any,
    spec: OperationSpec,
    resource: ResourceRef,
) -> None:
    """Bind a deliberately run-scoped service token to its one report resource."""
    if (
        spec.operation_name != "get_observatory_run_report"
        or principal.principal_type != "service"
        or RUN_REPORT_RESOURCE_ID_ATTRIBUTE not in principal.attributes
    ):
        return
    if principal.attributes[RUN_REPORT_RESOURCE_ID_ATTRIBUTE] != resource.resource_id:
        raise HTTPException(
            status_code=403,
            detail={"error": "forbidden", "reason": "run_report_scope_mismatch"},
        )


async def enforce_http_operation(
    request: Request,
    spec: OperationSpec,
    path_params: dict[str, str],
) -> None:
    """Authenticate and authorize a classified HTTP operation."""
    if spec.public:
        return

    # Access control runs when regulated mode is active OR production HTTP
    # authorization is required (ADR 0047). Otherwise unregulated development
    # keeps the historical behavior: RBAC is skipped, but run-scoped service
    # tokens remain confined to their single report.
    if not is_regulated() and not requires_http_authorization():
        if spec.operation_name == "get_observatory_run_report":
            auth_principal = get_request_principal(request)
            if (
                auth_principal is not None
                and auth_principal.principal_type == "service"
                and RUN_REPORT_RESOURCE_ID_ATTRIBUTE in auth_principal.attributes
            ):
                resource = await resolve_resource(request, spec, path_params)
                _enforce_scoped_run_report_service_identity(auth_principal, spec, resource)
        return

    auth_principal = get_request_principal(request)
    if auth_principal is None:
        _raise_unauthorized()

    spec = await _specialize_operation(request, spec)
    await _validate_request_payload(request, spec)
    resource = await resolve_resource(request, spec, path_params)
    _enforce_scoped_run_report_service_identity(auth_principal, spec, resource)
    context: DecisionContext = create_decision_context(request)
    correlation_id = get_request_correlation_id(request)

    if is_regulated():
        # Core enforce() owns the AuthPrincipal -> canonical Principal bridge.
        # Passing the API-layer Principal here loses groups and fails regulated
        # canonicalization for otherwise valid callers.
        result = enforce(
            principal=auth_principal,
            action=spec.action,
            resource=resource,
            context=context,
            request_id=correlation_id,
            surface="phlo-api",
            correlation_id=correlation_id,
        )
        if result.variant == "error":
            raise HTTPException(
                status_code=503,
                detail={"error": "service_unavailable", "reason": "authorization_unavailable"},
            )
        if not result.allowed:
            raise HTTPException(
                status_code=403,
                detail={"error": "forbidden", "reason": "access_denied"},
            )
        return

    principal = resolve_request_principal(request, require_auth=True)
    if principal is None:
        _raise_unauthorized()
    backend = get_authorization_backend()
    if backend is None:
        raise HTTPException(
            status_code=503,
            detail={"error": "service_unavailable", "reason": "authorization_unavailable"},
        )
    decision = backend.explain_decision(principal, spec.action, resource, context)
    if decision.reason_code == "backend_unavailable":
        raise HTTPException(
            status_code=503,
            detail={"error": "service_unavailable", "reason": "authorization_unavailable"},
        )
    if not decision.allowed:
        raise HTTPException(
            status_code=403,
            detail={"error": "forbidden", "reason": "access_denied"},
        )


async def _specialize_operation(request: Request, spec: OperationSpec) -> OperationSpec:
    """Resolve the action/resource pair for payload-dispatched operations."""
    if spec.operation_name not in {
        "post_observatory_action",
        "post_observatory_branch_action",
    }:
        return spec
    body = await _request_json(request)
    if not isinstance(body, dict):
        return spec
    action_id = body.get("action_id")
    if not isinstance(action_id, str) or not action_id:
        return spec

    def bind_identity(key: str, value: str) -> None:
        """Bind an identity value into the request body, rejecting conflicts."""
        existing = body.get(key)
        if existing is not None and str(existing) != value:
            raise HTTPException(status_code=400, detail={"error": "ambiguous_resource"})
        body[key] = value

    if spec.operation_name == "post_observatory_branch_action":
        parts = action_id.split(":", 2)
        if len(parts) != 3 or parts[0] != "branch" or not parts[2].strip():
            raise HTTPException(status_code=400, detail={"error": "invalid_action"})
        bind_identity("branch_name", parts[2].strip())
        request.state._phlo_security_body_override = body
        return replace(
            spec,
            resource_keys=("branch_name",),
            resource_sources=(("branch_name", "body"),),
        )

    if action_id.startswith("dataset:"):
        resource_id, separator, action_name = action_id.removeprefix("dataset:").rpartition(":")
        if not separator or not resource_id or action_name not in {"publish", "retire"}:
            raise HTTPException(status_code=400, detail={"error": "invalid_action"})
        action = (
            CanonicalAction.DATASET_PUBLISH.value
            if action_name == "publish"
            else CanonicalAction.DATASET_WRITE.value
        )
        resource_type = "dataset"
        keys = ("dataset_id",)
        bind_identity("dataset_id", resource_id)
    elif action_id.startswith("candidate:"):
        resource_id, separator, action_name = action_id.removeprefix("candidate:").rpartition(":")
        if not separator or not resource_id or action_name not in {"claim", "promote", "reject"}:
            raise HTTPException(status_code=400, detail={"error": "invalid_action"})
        action = CanonicalAction.DATASET_WRITE.value
        resource_type = "dataset"
        keys = ("table_id",)
        bind_identity("table_id", resource_id)
    elif action_id.startswith("asset:"):
        resource_id, separator, _action_name = action_id.removeprefix("asset:").rpartition(":")
        if not separator or not resource_id:
            raise HTTPException(status_code=400, detail={"error": "invalid_action"})
        action = CanonicalAction.ASSET_EXECUTE.value
        resource_type = "asset"
        keys = ("asset_id", "asset_key")
        bind_identity("asset_id", resource_id)
    elif action_id.startswith("branch:"):
        parts = action_id.split(":", 2)
        if len(parts) != 3 or not parts[2].strip():
            raise HTTPException(status_code=400, detail={"error": "invalid_action"})
        action = CanonicalAction.CATALOG_MANAGE.value
        resource_type = "catalog"
        keys = ("branch_name",)
        bind_identity("branch_name", parts[2].strip())
    elif action_id.startswith("workflow:"):
        resource_id, separator, _action_name = action_id.removeprefix("workflow:").rpartition(":")
        if not separator or not resource_id:
            raise HTTPException(status_code=400, detail={"error": "invalid_action"})
        action = CanonicalAction.OBJECT_WRITE.value
        resource_type = "object"
        keys = ("workflow_id", "path")
        bind_identity("workflow_id", resource_id)
    elif action_id.startswith("service:"):
        resource_id, separator, _action_name = action_id.removeprefix("service:").rpartition(":")
        if not separator or not resource_id:
            raise HTTPException(status_code=400, detail={"error": "invalid_action"})
        action = CanonicalAction.SERVICE_MANAGE.value
        resource_type = "service"
        keys = ("service_id", "name")
        bind_identity("service_id", resource_id)
    else:
        resource_id, separator, action_name = action_id.rpartition(":")
        if separator and action_name in {"add", "start", "stop", "restart"} and resource_id:
            action = CanonicalAction.SERVICE_MANAGE.value
            resource_type = "service"
            keys = ("service_id",)
            bind_identity("service_id", resource_id)
        else:
            action = CanonicalAction.ADMIN_MANAGE.value
            resource_type = "admin"
            keys = ("action_id",)
            bind_identity("action_id", action_id)

    request.state._phlo_security_body_override = body
    return replace(
        spec,
        action=action,
        resource_type=resource_type,
        resource_keys=keys,
        resource_sources=tuple((key, "body") for key in keys),
    )


async def _validate_request_payload(request: Request, spec: OperationSpec) -> None:
    """Reject unsupported query payloads before a data handler runs."""
    if spec.operation_name != "post_observatory_query":
        return
    body = await _request_json(request)
    if not isinstance(body, dict) or not isinstance(body.get("sql"), str):
        raise HTTPException(status_code=400, detail={"error": "invalid_query"})
    from phlo_api.observatory_api.observatory import is_supported_read_query

    if not is_supported_read_query(body["sql"]):
        raise HTTPException(status_code=400, detail={"error": "unsupported_query"})


def _reject_explicit_optional_in_production() -> None:
    """Reject an explicitly configured ``optional`` authorization mode in production.

    The unset default is resolved to ``required`` by ``get_authorization_mode()``;
    an explicit ``optional`` in production is a configuration contradiction and
    must fail startup with a clear error rather than being silently overridden.
    """
    explicit_mode = os.environ.get(_AUTHORIZATION_MODE_ENV)
    if explicit_mode is None:
        config = get_api_authorization_config()
        explicit_mode = config.mode if config is not None and config.mode is not None else None
    if (
        explicit_mode is not None
        and explicit_mode.strip().lower() == _AUTHORIZATION_MODE_OPTIONAL
        and requires_http_authorization()
    ):
        raise RuntimeError(
            f"{_AUTHORIZATION_MODE_ENV} cannot be {_AUTHORIZATION_MODE_OPTIONAL!r} "
            "when production HTTP authorization is required; set it to "
            f"{_AUTHORIZATION_MODE_REQUIRED!r}."
        )


def install_manifest_enforcement(app: Any) -> None:
    """Validate and install the mandatory pre-handler enforcement boundary."""
    validate_manifest(app)
    _reject_explicit_optional_in_production()

    @app.middleware("http")
    async def _manifest_middleware(request: Request, call_next: Any) -> Any:
        request_id = request.headers.get("x-request-id") or str(uuid4())
        request.state.request_id = request_id
        bind_context(request_id=request_id, path=request.url.path, method=request.method)
        try:
            # CORS preflight is a protocol negotiation request, not an
            # application operation; the actual request remains protected.
            if request.method == "OPTIONS":
                return await call_next(request)
            resolved = _route_for_request(app, request)
            if resolved is None:
                response = await call_next(request)
                response.headers.setdefault("x-request-id", request_id)
                return response
            spec, path_params = resolved
            try:
                await enforce_http_operation(request, spec, path_params)
            except HTTPException as exc:
                detail = exc.detail if isinstance(exc.detail, dict) else {"detail": exc.detail}
                response = JSONResponse(
                    status_code=exc.status_code,
                    content=detail,
                    headers=exc.headers,
                )
                response.headers.setdefault("x-request-id", request_id)
                return response
            except Exception:
                # Authentication and policy resolution are part of the
                # boundary. A provider or backend failure must not reach the
                # handler or become an accidental application 500.
                logger.exception("phlo_api_security_boundary_unavailable")
                response = JSONResponse(
                    status_code=503,
                    content={
                        "error": "service_unavailable",
                        "reason": "authorization_unavailable",
                    },
                )
                response.headers.setdefault("x-request-id", request_id)
                return response
            response = await call_next(request)
            response.headers.setdefault("x-request-id", request_id)
            return response
        finally:
            clear_context()


def validate_operation_registry() -> None:
    """Ensure this manifest only claims the HTTP boundary it actually installs."""
    if any(spec.surface != "http" for spec in HTTP_ROUTE_MANIFEST.values()):
        raise RuntimeError("Unenforced non-HTTP operation in the API manifest")


validate_operation_registry()
