/** Secure publisher for comments generated by the Phlo Amp review automation. */
import { timingSafeEqual } from 'node:crypto'
import { issueTriageLabelsAllowed } from './triage.ts'

const REPOSITORY = 'phlohouse/phlo'
const MAX_BODY_LENGTH = 60_000
const MAX_REQUEST_LENGTH = 80_000
const DELIVERY_PATTERN = /^[A-Za-z0-9:_-]{1,200}$/
const SHA_PATTERN = /^[0-9a-f]{40}$/i
const MARKER_PREFIX = '<!-- phlo-agent-delivery:'

export interface AmpPublishRequest {
  body: string
  deliveryId: string
  headSha?: string
  kind: 'issue' | 'pull_request'
  labels?: string[]
  number: number
  receivedAt: string
}

interface PublisherDependencies {
  fetch?: typeof fetch
  installationToken: () => Promise<string>
  publishToken?: string
  writesEnabled?: boolean
}

interface GitHubComment {
  body?: unknown
  html_url?: unknown
  id?: unknown
}

function constantTimeEqual(actual: string, expected: string): boolean {
  const actualBytes = Buffer.from(actual)
  const expectedBytes = Buffer.from(expected)
  return actualBytes.length === expectedBytes.length
    && timingSafeEqual(actualBytes, expectedBytes)
}

function bearerToken(request: Request): string | null {
  const authorization = request.headers.get('authorization')
  const match = authorization?.match(/^Bearer ([^\s]+)$/i)
  return match?.[1] ?? null
}

function parseRequest(value: unknown): AmpPublishRequest | null {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return null
  const input = value as Record<string, unknown>
  if (input.kind !== 'issue' && input.kind !== 'pull_request') return null
  if (!Number.isSafeInteger(input.number) || (input.number as number) < 1) return null
  if (typeof input.body !== 'string' || input.body.length === 0 || input.body.length > MAX_BODY_LENGTH) {
    return null
  }
  if (input.body.includes(MARKER_PREFIX)) return null
  if (typeof input.deliveryId !== 'string' || !DELIVERY_PATTERN.test(input.deliveryId)) return null
  if (typeof input.receivedAt !== 'string' || !Number.isFinite(Date.parse(input.receivedAt))) return null

  const labels = input.labels === undefined ? [] : input.labels
  if (!Array.isArray(labels) || !labels.every((label) => typeof label === 'string')) return null
  if (input.kind === 'pull_request') {
    if (typeof input.headSha !== 'string' || !SHA_PATTERN.test(input.headSha) || labels.length > 0) {
      return null
    }
  } else if (input.headSha !== undefined || (labels.length > 0 && !issueTriageLabelsAllowed(labels))) {
    return null
  }

  return {
    body: input.body,
    deliveryId: input.deliveryId,
    kind: input.kind,
    labels,
    number: input.number as number,
    receivedAt: input.receivedAt,
    ...(input.kind === 'pull_request' ? { headSha: input.headSha as string } : {}),
  }
}

function nextPage(link: string | null): string | null {
  if (link === null) return null
  for (const part of link.split(',')) {
    const match = part.match(/<([^>]+)>;\s*rel="next"/)
    if (match?.[1]) return match[1]
  }
  return null
}

async function githubRequest(
  request: RequestInfo | URL,
  token: string,
  fetcher: typeof fetch,
  init?: RequestInit,
): Promise<Response> {
  return fetcher(request, {
    ...init,
    headers: {
      accept: 'application/vnd.github+json',
      authorization: `Bearer ${token}`,
      'content-type': 'application/json',
      'x-github-api-version': '2022-11-28',
      ...init?.headers,
    },
  })
}

async function existingComment(
  input: AmpPublishRequest,
  token: string,
  fetcher: typeof fetch,
): Promise<GitHubComment | null> {
  const marker = `${MARKER_PREFIX}${input.deliveryId} -->`
  const since = encodeURIComponent(input.receivedAt)
  let url: string | null = `https://api.github.com/repos/${REPOSITORY}/issues/${input.number}/comments?per_page=100&since=${since}`

  while (url !== null) {
    const response = await githubRequest(url, token, fetcher)
    if (!response.ok) throw new Error(`GitHub comment lookup failed with HTTP ${response.status}.`)
    const comments = await response.json() as GitHubComment[]
    const found = comments.find((comment) =>
      typeof comment.body === 'string' && comment.body.includes(marker),
    )
    if (found !== undefined) return found
    url = nextPage(response.headers.get('link'))
  }
  return null
}

async function publish(
  input: AmpPublishRequest,
  token: string,
  fetcher: typeof fetch,
): Promise<{ htmlUrl: string; reused: boolean }> {
  if (input.kind === 'pull_request') {
    const response = await githubRequest(
      `https://api.github.com/repos/${REPOSITORY}/pulls/${input.number}`,
      token,
      fetcher,
    )
    if (!response.ok) throw new Error(`GitHub pull request lookup failed with HTTP ${response.status}.`)
    const pullRequest = await response.json() as { head?: { sha?: unknown } }
    if (pullRequest.head?.sha !== input.headSha) {
      throw new Error('The pull request head changed after the review started.')
    }
  }

  const duplicate = await existingComment(input, token, fetcher)
  if (duplicate !== null) {
    return {
      htmlUrl: typeof duplicate.html_url === 'string' ? duplicate.html_url : '',
      reused: true,
    }
  }

  if (input.kind === 'issue' && input.labels !== undefined && input.labels.length > 0) {
    const response = await githubRequest(
      `https://api.github.com/repos/${REPOSITORY}/issues/${input.number}/labels`,
      token,
      fetcher,
      { method: 'POST', body: JSON.stringify({ labels: input.labels }) },
    )
    if (!response.ok) throw new Error(`GitHub label update failed with HTTP ${response.status}.`)
  }

  const marker = `${MARKER_PREFIX}${input.deliveryId} -->`
  const response = await githubRequest(
    `https://api.github.com/repos/${REPOSITORY}/issues/${input.number}/comments`,
    token,
    fetcher,
    { method: 'POST', body: JSON.stringify({ body: `${input.body}\n\n${marker}` }) },
  )
  if (!response.ok) throw new Error(`GitHub comment creation failed with HTTP ${response.status}.`)
  const comment = await response.json() as GitHubComment
  return {
    htmlUrl: typeof comment.html_url === 'string' ? comment.html_url : '',
    reused: false,
  }
}

export async function handleAmpPublishRequest(
  request: Request,
  dependencies: PublisherDependencies,
): Promise<Response> {
  if (!dependencies.writesEnabled) {
    return Response.json({ error: 'Amp publishing is disabled.' }, { status: 503 })
  }
  const suppliedToken = bearerToken(request)
  if (
    dependencies.publishToken === undefined
    || dependencies.publishToken.length < 32
    || suppliedToken === null
    || !constantTimeEqual(suppliedToken, dependencies.publishToken)
  ) {
    return Response.json({ error: 'Unauthorized.' }, { status: 401 })
  }

  const contentLength = Number(request.headers.get('content-length'))
  if (Number.isFinite(contentLength) && contentLength > MAX_REQUEST_LENGTH) {
    return Response.json({ error: 'Request body is too large.' }, { status: 413 })
  }
  const rawBody = await request.text()
  if (rawBody.length > MAX_REQUEST_LENGTH) {
    return Response.json({ error: 'Request body is too large.' }, { status: 413 })
  }

  let json: unknown
  try {
    json = JSON.parse(rawBody)
  } catch {
    return Response.json({ error: 'Invalid JSON.' }, { status: 400 })
  }
  const input = parseRequest(json)
  if (input === null) return Response.json({ error: 'Invalid publish request.' }, { status: 400 })

  try {
    const token = await dependencies.installationToken()
    const result = await publish(input, token, dependencies.fetch ?? fetch)
    return Response.json(result, { status: result.reused ? 200 : 201 })
  } catch (error) {
    const message = error instanceof Error ? error.message : 'GitHub publishing failed.'
    const status = message.includes('head changed') ? 409 : 502
    return Response.json({ error: message }, { status })
  }
}
