// phlo: no-header

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as DatasetsSplatRouteImport } from './routes/datasets/$'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as ApiObservatorySplatRouteImport } from './routes/api/observatory/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsSplatRoute = DatasetsSplatRouteImport.update({
  id: '/datasets/$',
  path: '/datasets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservatorySplatRoute = ApiObservatorySplatRouteImport.update({
  id: '/api/observatory/$',
  path: '/api/observatory/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/governance': typeof GovernanceRoute
  '/platform': typeof PlatformRoute
  '/reference': typeof ReferenceRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/datasets/$': typeof DatasetsSplatRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/api/observatory/$': typeof ApiObservatorySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/governance': typeof GovernanceRoute
  '/platform': typeof PlatformRoute
  '/reference': typeof ReferenceRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/datasets/$': typeof DatasetsSplatRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/datasets': typeof DatasetsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/api/observatory/$': typeof ApiObservatorySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/governance': typeof GovernanceRoute
  '/platform': typeof PlatformRoute
  '/reference': typeof ReferenceRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/datasets/$': typeof DatasetsSplatRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/api/observatory/$': typeof ApiObservatorySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/governance'
    | '/platform'
    | '/reference'
    | '/releases'
    | '/settings'
    | '/datasets/$'
    | '/runs/$runId'
    | '/datasets/'
    | '/runs/'
    | '/api/observatory/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/governance'
    | '/platform'
    | '/reference'
    | '/releases'
    | '/settings'
    | '/datasets/$'
    | '/runs/$runId'
    | '/datasets'
    | '/runs'
    | '/api/observatory/$'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/governance'
    | '/platform'
    | '/reference'
    | '/releases'
    | '/settings'
    | '/datasets/$'
    | '/runs/$runId'
    | '/datasets/'
    | '/runs/'
    | '/api/observatory/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  GovernanceRoute: typeof GovernanceRoute
  PlatformRoute: typeof PlatformRoute
  ReferenceRoute: typeof ReferenceRoute
  ReleasesRoute: typeof ReleasesRoute
  SettingsRoute: typeof SettingsRoute
  DatasetsSplatRoute: typeof DatasetsSplatRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  ApiObservatorySplatRoute: typeof ApiObservatorySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$': {
      id: '/datasets/$'
      path: '/datasets/$'
      fullPath: '/datasets/$'
      preLoaderRoute: typeof DatasetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observatory/$': {
      id: '/api/observatory/$'
      path: '/api/observatory/$'
      fullPath: '/api/observatory/$'
      preLoaderRoute: typeof ApiObservatorySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  GovernanceRoute: GovernanceRoute,
  PlatformRoute: PlatformRoute,
  ReferenceRoute: ReferenceRoute,
  ReleasesRoute: ReleasesRoute,
  SettingsRoute: SettingsRoute,
  DatasetsSplatRoute: DatasetsSplatRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  ApiObservatorySplatRoute: ApiObservatorySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
