/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DatasetsOrdersRouteImport } from './routes/datasets/orders'
import { Route as RunsOrdersDailyRouteImport } from './routes/runs/orders-daily'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsOrdersRoute = DatasetsOrdersRouteImport.update({
  id: '/datasets/orders',
  path: '/datasets/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsOrdersDailyRoute = RunsOrdersDailyRouteImport.update({
  id: '/runs/orders-daily',
  path: '/runs/orders-daily',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/governance': typeof GovernanceRoute
  '/platform': typeof PlatformRoute
  '/reference': typeof ReferenceRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/datasets/orders': typeof DatasetsOrdersRoute
  '/runs/orders-daily': typeof RunsOrdersDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/governance': typeof GovernanceRoute
  '/platform': typeof PlatformRoute
  '/reference': typeof ReferenceRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/datasets/orders': typeof DatasetsOrdersRoute
  '/runs/orders-daily': typeof RunsOrdersDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/governance': typeof GovernanceRoute
  '/platform': typeof PlatformRoute
  '/reference': typeof ReferenceRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/datasets/orders': typeof DatasetsOrdersRoute
  '/runs/orders-daily': typeof RunsOrdersDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/governance'
    | '/platform'
    | '/reference'
    | '/releases'
    | '/settings'
    | '/datasets/orders'
    | '/runs/orders-daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/governance'
    | '/platform'
    | '/reference'
    | '/releases'
    | '/settings'
    | '/datasets/orders'
    | '/runs/orders-daily'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/governance'
    | '/platform'
    | '/reference'
    | '/releases'
    | '/settings'
    | '/datasets/orders'
    | '/runs/orders-daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  GovernanceRoute: typeof GovernanceRoute
  PlatformRoute: typeof PlatformRoute
  ReferenceRoute: typeof ReferenceRoute
  ReleasesRoute: typeof ReleasesRoute
  SettingsRoute: typeof SettingsRoute
  DatasetsOrdersRoute: typeof DatasetsOrdersRoute
  RunsOrdersDailyRoute: typeof RunsOrdersDailyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/orders': {
      id: '/datasets/orders'
      path: '/datasets/orders'
      fullPath: '/datasets/orders'
      preLoaderRoute: typeof DatasetsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/orders-daily': {
      id: '/runs/orders-daily'
      path: '/runs/orders-daily'
      fullPath: '/runs/orders-daily'
      preLoaderRoute: typeof RunsOrdersDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  GovernanceRoute: GovernanceRoute,
  PlatformRoute: PlatformRoute,
  ReferenceRoute: ReferenceRoute,
  ReleasesRoute: ReleasesRoute,
  SettingsRoute: SettingsRoute,
  DatasetsOrdersRoute: DatasetsOrdersRoute,
  RunsOrdersDailyRoute: RunsOrdersDailyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
