version: 2
sources:
  - name: ch_raw
    database: raw
    schema: raw
    tables:
      - name: platform_events
        meta:
          phlo_asset_key: dlt_platform_events
      - name: access_logs
        meta:
          phlo_asset_key: dlt_access_logs
      - name: chmeta_tenants
        meta:
          phlo_asset_key: sling_chmeta_tenants
