#!/usr/bin/env python3
"""Generate deterministic Markdown and JSON reference documentation."""

from __future__ import annotations

import argparse
import ast
import importlib
import json
import os
import sys
import tempfile
import tomllib
from collections.abc import Callable, Mapping, Sequence
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
METHODS = ("delete", "get", "head", "options", "patch", "post", "put", "trace")


def roots(root: Path) -> list[Path]:
    return [root / "src", *sorted((root / "packages").glob("*/src"))]


def prepare_imports(root: Path) -> None:
    for path in reversed(roots(root)):
        value = str(path)
        if value not in sys.path:
            sys.path.insert(0, value)


def safe(value: object) -> object:
    if value is None or isinstance(value, str | int | float | bool):
        return value
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, Mapping):
        return {
            str(key): safe(item)
            for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))
        }
    if isinstance(value, set | frozenset):
        return sorted((safe(item) for item in value), key=repr)
    if isinstance(value, tuple | list):
        return [safe(item) for item in value]
    if callable(value):
        return f"<factory:{getattr(value, '__qualname__', type(value).__name__)}>"
    return repr(value)


def cell(value: object) -> str:
    if value is None:
        return "none"
    if value == "":
        return '""'
    text = (
        value if isinstance(value, str) else json.dumps(value, sort_keys=True, ensure_ascii=False)
    )
    return text.replace("|", "\\|").replace("\n", " ")


def cli_docs(root: Path) -> tuple[dict[str, object], str]:
    prepare_imports(root)
    try:
        from phlo.cli.commands.commands import describe_commands
        from phlo.cli.main import cli
    except Exception as exc:
        raise RuntimeError(f"Cannot load the CLI contract: {exc}") from exc
    commands = describe_commands(cli)
    concrete: dict[str, Any] = {}

    def visit(command: Any, path: list[str]) -> None:
        concrete[" ".join(path)] = command
        for name, child in sorted(getattr(command, "commands", {}).items()):
            if not child.hidden:
                visit(child, [*path, name])

    visit(cli, ["phlo"])
    for command in commands:
        for parameter, actual in zip(
            command["parameters"], concrete[command["command"]].params, strict=True
        ):
            parameter.update(default=safe(actual.default), envvar=safe(actual.envvar))
    commands.sort(key=lambda item: item["command"])
    data: dict[str, object] = {
        "schema_version": 1,
        "command_count": len(commands),
        "commands": commands,
    }
    lines = [
        "# CLI reference",
        "",
        "> Generated by `scripts/generate_reference_docs.py`. Do not edit this page directly.",
        "",
        f"This page lists all {len(commands)} installed command paths. The generator reads the Click contract without running a command.",
        "",
        "Run `python scripts/generate_reference_docs.py` to regenerate this page and `generated/cli.json`.",
        "",
    ]
    for command in commands:
        lines += [f"## `{command['command']}`", "", command["description"] or "No description.", ""]
        capabilities = command["capabilities"]
        lines += [
            "Capabilities: "
            + ", ".join(f"`{key}={str(value).lower()}`" for key, value in capabilities.items()),
            "",
        ]
        if not command["parameters"]:
            lines += ["Parameters: none.", ""]
            continue
        lines += [
            "| Name | Kind | Options | Type | Required | Default | Other |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        for parameter in command["parameters"]:
            options = [*parameter.get("options", []), *parameter.get("secondary_options", [])]
            details = []
            if parameter.get("choices"):
                details.append("choices: " + ", ".join(map(str, parameter["choices"])))
            if parameter.get("multiple"):
                details.append("multiple")
            if parameter.get("is_flag"):
                details.append("flag")
            if parameter.get("nargs") != 1:
                details.append(f"nargs={parameter['nargs']}")
            if parameter.get("envvar"):
                details.append(f"env: {cell(parameter['envvar'])}")
            lines.append(
                f"| `{parameter['name']}` | {parameter['kind']} | "
                f"{' '.join(f'`{option}`' for option in options) or 'none'} | `{parameter['type']}` | "
                f"{str(parameter['required']).lower()} | `{cell(parameter['default'])}` | {'; '.join(details) or 'none'} |"
            )
        lines.append("")
    return data, "\n".join(lines).rstrip() + "\n"


def setting_candidates(root: Path) -> list[tuple[Path, str]]:
    found = []
    for source in roots(root):
        for path in sorted(source.rglob("*.py")):
            try:
                tree = ast.parse(path.read_text(encoding="utf-8"))
            except (OSError, SyntaxError):
                continue
            for node in tree.body:
                if isinstance(node, ast.ClassDef) and any(
                    isinstance(base, ast.Name) and base.id in {"BaseConfig", "BaseSettings"}
                    for base in node.bases
                ):
                    found.append((path, node.name))
    return found


def module_details(root: Path, path: Path) -> tuple[str, str]:
    source = next(candidate for candidate in roots(root) if path.is_relative_to(candidate))
    module = ".".join(path.relative_to(source).with_suffix("").parts)
    project = (
        root / "pyproject.toml" if source == root / "src" else source.parent / "pyproject.toml"
    )
    with project.open("rb") as file:
        package = tomllib.load(file)["project"]["name"]
    return module, package


def settings_docs(root: Path) -> tuple[dict[str, object], str]:
    prepare_imports(root)
    models = []
    for path, class_name in setting_candidates(root):
        module_name, package = module_details(root, path)
        model: dict[str, Any] = {
            "package": package,
            "module": module_name,
            "class": class_name,
            "source": str(path.relative_to(root)),
        }
        try:
            cls = getattr(importlib.import_module(module_name), class_name)
            fields = []
            for name, field in sorted(cls.model_fields.items()):
                if field.default_factory is not None:
                    default: object = safe(field.default_factory)
                elif field.is_required():
                    default = "<required>"
                else:
                    default = safe(field.default)
                fields.append(
                    {
                        "name": name,
                        "alias": safe(field.validation_alias or field.alias or name),
                        "annotation": str(field.annotation).replace("typing.", ""),
                        "required": field.is_required(),
                        "default": default,
                        "description": field.description,
                    }
                )
            model.update(status="introspected", fields=fields)
        except Exception as exc:
            model.update(status="unavailable", fields=[], error=f"{type(exc).__name__}: {exc}")
        models.append(model)
    models.sort(key=lambda item: (item["package"], item["module"], item["class"]))
    field_count = sum(len(model["fields"]) for model in models)
    unavailable = sum(model["status"] != "introspected" for model in models)
    data: dict[str, object] = {
        "schema_version": 1,
        "model_count": len(models),
        "field_count": field_count,
        "unavailable_model_count": unavailable,
        "models": models,
    }
    lines = [
        "# Settings reference",
        "",
        "> Generated by `scripts/generate_reference_docs.py`. Do not edit this page directly.",
        "",
        f"This inventory contains {field_count} fields from {len(models)} Pydantic settings models. {unavailable} models could not be introspected.",
        "",
        "Defaults come from model metadata. The generator does not instantiate settings or read environment values. Passwords and keys shown here are public development defaults from source code, not deployed secret values; replace them outside local development.",
        "",
    ]
    for model in models:
        lines += [
            f"## `{model['package']}`: `{model['class']}`",
            "",
            f"Source: `{model['source']}`",
            "",
        ]
        if model["status"] != "introspected":
            lines += [f"Introspection unavailable: `{cell(model['error'])}`", ""]
            continue
        if not model["fields"]:
            lines += ["This model declares no fields.", ""]
            continue
        lines += [
            "| Field | Alias | Type | Required | Default | Description |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for field in model["fields"]:
            lines.append(
                f"| `{field['name']}` | `{cell(field['alias'])}` | `{cell(field['annotation'])}` | {str(field['required']).lower()} | `{cell(field['default'])}` | {cell(field['description'])} |"
            )
        lines.append("")
    return data, "\n".join(lines).rstrip() + "\n"


def http_docs(root: Path) -> tuple[dict[str, object], str]:
    prepare_imports(root)
    try:
        from phlo_api.main import app

        schema = app.openapi()
    except Exception as exc:
        raise RuntimeError(f"Cannot load FastAPI OpenAPI from phlo_api.main: {exc}") from exc
    endpoints = []
    for path, operations in sorted(schema["paths"].items()):
        for method in METHODS:
            if method in operations:
                operation = operations[method]
                endpoints.append(
                    {
                        "method": method.upper(),
                        "path": path,
                        "summary": operation.get("summary", ""),
                        "tags": sorted(operation.get("tags", [])),
                        "operation_id": operation.get("operationId"),
                    }
                )
    endpoints.sort(key=lambda item: (item["path"], item["method"]))
    data: dict[str, object] = {
        "schema_version": 1,
        "api": schema["info"],
        "endpoint_count": len(endpoints),
        "endpoints": endpoints,
    }
    lines = [
        "# HTTP API reference",
        "",
        "> Generated by `scripts/generate_reference_docs.py`. Do not edit the endpoint inventory directly.",
        "",
        "## Contract",
        "",
        "The API reports version `0.1.0` in OpenAPI. Phase 1 introduces `/api/v1` alongside unchanged legacy paths. Treat the API as alpha because the support manifest marks the current release as alpha.",
        "",
        "`/health` is public. The security manifest classifies every other route as protected. `/api/v1` always requires identity and authorization; legacy authorization can be optional outside regulated and production modes. See [Authentication and access](auth-and-access.md) for configuration.",
        "",
        f"## Endpoints ({len(endpoints)})",
        "",
        "| Method | Path | Summary | Tags |",
        "| --- | --- | --- | --- |",
    ]
    for item in endpoints:
        lines.append(
            f"| `{item['method']}` | `{item['path']}` | {cell(item['summary'])} | {', '.join(f'`{tag}`' for tag in item['tags']) or 'none'} |"
        )
    return data, "\n".join(lines).rstrip() + "\n"


def support_docs(root: Path) -> tuple[dict[str, object], str]:
    manifest = json.loads((root / "registry/support/v1.json").read_text(encoding="utf-8"))
    gate_map = {item["name"]: item for item in manifest["gates"]["components"]}
    components = []
    for plural, singular in (
        ("packages", "package"),
        ("services", "service"),
        ("capabilities", "capability"),
    ):
        for item in manifest[plural]:
            name = f"{singular}:{item['name']}"
            gate = gate_map.get(name, {})
            components.append(
                {
                    "component": name,
                    "target_profile": item.get("scope", "not specified"),
                    "target_status": item.get("target_status", "not specified"),
                    "current_maturity": item.get(
                        "current_maturity", manifest["current_release"]["maturity"]
                    ),
                    "readiness": gate.get("status", "not gated"),
                    "applicable_gates": gate.get("applicable_gates", []),
                    "blockers": gate.get("blocked_by", []),
                }
            )
    components.sort(key=lambda item: item["component"])
    data: dict[str, object] = {
        "schema_version": 1,
        "release": manifest["current_release"],
        "gate_status": manifest["gates"]["status"],
        "component_count": len(components),
        "components": components,
    }
    release = manifest["current_release"]
    lines = [
        "# Support matrix",
        "",
        "> Generated from `registry/support/v1.json` by `scripts/generate_reference_docs.py`. Do not edit this page directly.",
        "",
        f"Release `{release['version']}` has `{release['maturity']}` maturity. Production readiness is `{str(release['production_ready']).lower()}`.",
        "",
        "A target profile states the intended support boundary. Maturity and readiness state what is available now. Gates and blockers state what must pass before release.",
        "",
    ]
    for prefix, heading in (
        ("capability:", "Capabilities"),
        ("package:", "Packages"),
        ("service:", "Services"),
    ):
        lines += [f"## {heading}", ""]
        for item in (entry for entry in components if entry["component"].startswith(prefix)):
            name = item["component"].removeprefix(prefix)
            gates = ", ".join(f"`{gate}`" for gate in item["applicable_gates"]) or "none"
            blockers = ", ".join(f"`{blocker}`" for blocker in item["blockers"]) or "none"
            lines += [
                f"### `{name}`",
                "",
                f"- Target profile: `{item['target_profile']}`; target status: `{item['target_status']}`.",
                f"- Current maturity: `{item['current_maturity']}`; readiness: `{item['readiness']}`.",
                f"- Applicable gates: {gates}.",
                f"- Blockers: {blockers}.",
                "",
            ]
    return data, "\n".join(lines).rstrip() + "\n"


def outputs(root: Path) -> dict[Path, str]:
    destination = root / "docs/reference"
    result = {}
    builders: tuple[tuple[str, Callable[[Path], tuple[dict[str, object], str]]], ...] = (
        ("cli", cli_docs),
        ("settings", settings_docs),
        ("http-api", http_docs),
        ("support-matrix", support_docs),
    )
    for name, builder in builders:
        data, markdown = builder(root)
        result[destination / f"{name}.md"] = markdown
        result[destination / "generated" / f"{name}.json"] = (
            json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
        )
    return result


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    temporary = Path(name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as file:
            file.write(content)
            file.flush()
            os.fsync(file.fileno())
        temporary.replace(path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def write_outputs(rendered: Mapping[Path, str], *, check: bool) -> list[Path]:
    changed = [
        path
        for path, content in rendered.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if not check:
        for path in changed:
            atomic_write(path, rendered[path])
    return changed


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Report stale generated files without writing them."
    )
    args = parser.parse_args(argv)
    try:
        changed = write_outputs(outputs(ROOT), check=args.check)
    except Exception as exc:
        parser.exit(1, f"reference generation failed: {exc}\n")
    if args.check and changed:
        paths = "\n".join(f"  {path.relative_to(ROOT)}" for path in changed)
        parser.exit(
            1,
            f"generated reference documentation is stale:\n{paths}\nRun: python scripts/generate_reference_docs.py\n",
        )
    print(
        f"Reference documentation {'updated' if changed else 'already current'}: {len(changed)} file(s)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
