"""Registers the OAuth2 Proxy service plugin.

The plugin class is generated by ``service_plugin_class`` and carries
identity metadata only.
Loaded through the phlo plugin entry-point mechanism at startup rather than
imported directly; declares service metadata against phlo.plugins.
"""

from __future__ import annotations

from phlo.plugins import service_plugin_class


Oauth2ProxyServicePlugin = service_plugin_class(
    "Oauth2ProxyServicePlugin",
    name="oauth2-proxy",
    version="0.1.0",
    description="OAuth2/OIDC authentication proxy for Phlo services",
    author="Phlo Team",
    tags=["auth", "proxy", "oidc"],
)
