"""
Compose Generator Module

Generates docker-compose.yml and .env/.env.local files from service definitions.
"""

import os
import platform
import re
import shutil
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Literal

import yaml

from phlo.config_schema import ServiceOverride
from phlo.logging import get_logger
from phlo.plugins.compose.env import (
    generate_env as _generate_env,
)
from phlo.plugins.compose.env import (
    generate_env_local as _generate_env_local,
)
from phlo.plugins.discovery import ServiceDefinition, ServiceDiscovery

logger = get_logger(__name__)


# These are implementation backends, rather than regulated user entry points.
# Dagster remains reachable in the production profile because its webserver is a
# regulated operator surface.  Keep this list deliberately small: applying it
# to an entry point would silently remove its supported route.
_PRODUCTION_INTERNAL_SERVICES = frozenset({"postgres", "minio", "nessie", "trino"})
_PRODUCTION_CREDENTIAL_DEFAULTS = {
    "POSTGRES_USER": "phlo",
    "POSTGRES_PASSWORD": "phlo",
    "MINIO_ROOT_USER": "minio",
    "MINIO_ROOT_PASSWORD": "minio123",
}
# Project lock metadata staged into the generated build context for uv-managed
# projects; kept out of version control because the project root owns the
# source of truth (see `phlo services init`).
UV_LOCK_METADATA_FILES = ("pyproject.toml", "uv.lock")
_EMPTY_DEFAULT_ENVIRONMENT_EXPRESSION = re.compile(r"^\$\{([A-Za-z_][A-Za-z0-9_]*):-\}$")


class ComposeGenerator:
    """Generates docker-compose.yml from service definitions."""

    def __init__(self, discovery: ServiceDiscovery):
        """Initialize with a service discovery instance."""
        self.discovery = discovery

    def generate_compose(
        self,
        services: list[ServiceDefinition],
        output_dir: Path,
        dev_mode: bool = False,
        service_dev_mode: bool = False,
        phlo_src_path: str | None = None,
        user_overrides: dict[str, Any] | None = None,
        env_values: Mapping[str, Any] | None = None,
        deployment_profile: Literal["development", "production"] = "development",
    ) -> str:
        """Generate docker-compose.yml content for the given services.
        dev_mode adds Phlo source mounts for dev services and
        service_dev_mode applies per-service ``dev:`` overrides; neither is
        allowed with the "production" deployment profile.
        """
        if deployment_profile == "production" and (dev_mode or service_dev_mode):
            raise ValueError(
                "production deployment profile cannot use dev_mode or service_dev_mode"
            )

        # Sort services by dependencies
        sorted_services = self.discovery.resolve_dependencies(services)
        user_overrides = user_overrides or {}
        env_values = env_values or {}

        compose: dict[str, Any] = {"services": {}}

        for service in sorted_services:
            # Get user override for this service (if any)
            service_override = user_overrides.get(service.name, {})

            compose["services"][service.name] = self._build_service_config(
                service,
                output_dir,
                dev_mode=dev_mode,
                service_dev_mode=service_dev_mode,
                phlo_src_path=phlo_src_path,
                user_override=service_override,
                env_values=env_values,
            )
            if deployment_profile == "production":
                self._apply_production_profile(service.name, compose["services"][service.name])

        if deployment_profile == "production":
            self._validate_workload_identity_references(env_values or {})

        named_volumes = self._collect_named_volumes(compose["services"].values())
        if named_volumes:
            compose["volumes"] = {name: {} for name in sorted(named_volumes)}

        # Add header comment with dev mode flag for stale detection
        dev_mode_str = "true" if dev_mode else "false"
        header = f"""# Phlo Infrastructure Stack
# Generated by: phlo services init
# Dev mode: {dev_mode_str}
# Modify phlo.yaml (env:) for defaults and .phlo/.env.local for secrets

"""
        return header + yaml.dump(compose, default_flow_style=False, sort_keys=False)

    def _apply_production_profile(self, service_name: str, config: dict[str, Any]) -> None:
        """Apply the bounded production network and credential posture."""
        if service_name in _PRODUCTION_INTERNAL_SERVICES:
            config.pop("ports", None)
            self._remove_traefik_labels(config)
        self._require_production_credentials(config)

    def _validate_workload_identity_references(self, env_values: Mapping[str, str]) -> None:
        """Reject shared or default/root workload credentials in production rendering.

        Uses the neutral workload-identity matrix so core never parses provider
        internals. Missing references are reported by the production preflight;
        this rendering check fails fast on refs that are present but insecure.
        """
        from phlo.security.workload_identities import evaluate_workload_identity_references

        failed = [
            evaluation
            for evaluation in evaluate_workload_identity_references(env_values)
            if not evaluation.passed and (evaluation.insecure_default or evaluation.shared_with)
        ]
        if failed:
            rendered = "; ".join(evaluation.message() for evaluation in failed)
            raise ValueError(
                f"production workload identities are not distinct or secure: {rendered}"
            )

    def _remove_traefik_labels(self, config: dict[str, Any]) -> None:
        """Remove public Traefik routes while retaining unrelated service labels."""
        labels = config.get("labels")
        if isinstance(labels, dict):
            config["labels"] = {
                key: value for key, value in labels.items() if not str(key).startswith("traefik.")
            }
        elif isinstance(labels, list):
            config["labels"] = [
                label
                for label in labels
                if not isinstance(label, str) or not label.startswith("traefik.")
            ]

    def _required_credential_expression(self, variable: str) -> str:
        return f"${{{variable}:?Phlo production requires {variable}}}"

    def _require_production_environment_assignment(self, value: Any) -> Any:
        """Normalize a protected list-form environment assignment."""
        if isinstance(value, str):
            variable, separator, _assigned_value = value.partition("=")
            if variable in _PRODUCTION_CREDENTIAL_DEFAULTS and (separator or value == variable):
                return f"{variable}={self._required_credential_expression(variable)}"
        return self._require_production_credentials(value)

    def _require_production_credentials(self, value: Any) -> Any:
        """Replace bundled credential fallbacks with Compose required-variable syntax.

        Rewrites happen in place on the generated config. Two shapes carry
        credentials: dict/list entries keyed or assigned by variable name, and
        string interpolation with a bundled default (``${VAR:-default}``). Both
        are converted to ``${VAR:?...}`` so Compose fails the stack instead of
        silently starting with a known default password.
        """
        if isinstance(value, dict):
            for key, nested_value in value.items():
                if key in _PRODUCTION_CREDENTIAL_DEFAULTS:
                    value[key] = self._required_credential_expression(key)
                elif key == "environment" and isinstance(nested_value, list):
                    value[key] = [
                        self._require_production_environment_assignment(item)
                        for item in nested_value
                    ]
                else:
                    value[key] = self._require_production_credentials(nested_value)
            return value
        if isinstance(value, list):
            return [self._require_production_credentials(item) for item in value]
        if not isinstance(value, str):
            return value

        for variable, default in _PRODUCTION_CREDENTIAL_DEFAULTS.items():
            bundled = f"${{{variable}:-{default}}}"
            if bundled in value:
                required = self._required_credential_expression(variable)
                value = value.replace(bundled, required)
        return value

    def _collect_named_volumes(self, services: Any) -> set[str]:
        """Collect named service volumes that need top-level compose declarations."""
        named_volumes: set[str] = set()
        for service in services:
            for volume in service.get("volumes", []):
                name = self._named_volume_from_mount(volume)
                if name:
                    named_volumes.add(name)
        return named_volumes

    def _named_volume_from_mount(self, volume: Any) -> str | None:
        """Return the named volume source for a short-syntax mount, if any."""
        if not isinstance(volume, str) or ":" not in volume:
            return None

        # Check for Windows drive-letter prefix (e.g., "C:\path")
        if len(volume) >= 2 and volume[0].isalpha() and volume[1] == ":":
            return None

        source = volume.split(":", 1)[0]
        if not source:
            return None
        if source.startswith((".", "/", "~", "$", "{")):
            return None
        if source.startswith("${"):
            return None

        return source

    def _build_service_config(
        self,
        service: ServiceDefinition,
        output_dir: Path,
        dev_mode: bool = False,
        service_dev_mode: bool = False,
        phlo_src_path: str | None = None,
        user_override: dict[str, Any] | None = None,
        env_values: Mapping[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Build the docker-compose configuration for one service, applying
        optional user overrides from phlo.yaml and conditional settings from
        effective environment values.
        """
        config: dict[str, Any] = {}
        user_override = user_override or {}

        # Image or build
        if service.image:
            config["image"] = service.image
        if service.build:
            # Determine build context
            context = service.build.get("context", ".")
            if context == "source" and service.source_path:
                # Use the service's source directory as build context
                context = str(service.source_path)
            if isinstance(context, str):
                context_path = Path(context)
                if context_path.is_absolute():
                    context = os.path.relpath(context_path, output_dir)
            build_config: dict[str, Any] = {"context": context}
            if service.build.get("dockerfile"):
                build_config["dockerfile"] = service.build["dockerfile"]
            if service.build.get("args"):
                build_config["args"] = service.build["args"]
            config["build"] = build_config

        # Profile (if not default)
        if service.profile:
            config["profiles"] = [service.profile]

        # Compose configuration
        compose = service.compose

        config["restart"] = compose.get("restart", "unless-stopped")

        handled_compose_keys = {
            "restart",
            "volumes",
            "command",
            "entrypoint",
            "healthcheck",
            "profiles",
            "env_file",
            "build",
            "depends_on",
            "conditional_environment",
        }

        for key in ("user", "container_name", "labels", "environment", "ports"):
            if compose.get(key):
                value = compose[key]
                if key == "environment" and isinstance(value, (dict, list)):
                    config[key] = value.copy()
                else:
                    config[key] = value
                handled_compose_keys.add(key)

        if compose.get("volumes"):
            config["volumes"] = list(compose["volumes"])  # Copy to avoid mutation
        else:
            config["volumes"] = []

        # Dev mode: inject phlo source mount and project directory for dependency sync
        if dev_mode and service.phlo_dev and phlo_src_path:
            # Mount the phlo monorepo root for editable installs inside the container.
            # `phlo_src_path` points at `.../src/phlo`, so `../..` is the repo root.
            project_mount = f"{phlo_src_path}/../..:/opt/phlo-dev:rw"
            config["volumes"].append(project_mount)
            # Do not silently reuse a published service image in a development
            # stack: it cannot include the checked-out adapter's runtime
            # dependencies. With no explicit image Compose builds the generated
            # Dockerfile before starting the mounted source tree.
            config.pop("image", None)
            # Add environment variable to enable dev mode sync
            if "environment" not in config:
                config["environment"] = {}
            if isinstance(config["environment"], dict):
                config["environment"]["PHLO_DEV_MODE"] = "true"
            elif isinstance(config["environment"], list):
                config["environment"].append("PHLO_DEV_MODE=true")

        # Remove empty volumes list
        if not config["volumes"]:
            del config["volumes"]

        if service_dev_mode and service.dev:
            self._apply_dev_overrides(config, service, output_dir)

        # Add env_file for phlo_dev services to pick up project secrets (e.g., GITHUB_TOKEN)
        # Path is relative to .phlo/ directory where docker-compose.yml lives
        if service.phlo_dev:
            config["env_file"] = [".env", ".env.local"]

        if compose.get("command"):
            config["command"] = compose["command"]

        if compose.get("entrypoint"):
            config["entrypoint"] = compose["entrypoint"]

        if compose.get("healthcheck"):
            config["healthcheck"] = compose["healthcheck"]

        # Pass through remaining compose keys such as mem_limit/cpus/ulimits.
        # This keeps generator behavior future-proof for valid docker-compose options.
        for key, value in compose.items():
            if key in handled_compose_keys:
                continue
            if value is None:
                continue
            config[key] = value

        if service.name in {"dagster", "dagster-daemon"}:
            if platform.system() == "Linux":
                # Start as root so the entrypoint can install the mounted project's
                # dependencies, then drop to the host identity before Dagster starts.
                config.pop("user", None)
                environment = config.setdefault("environment", {})
                if isinstance(environment, dict):
                    environment.setdefault("HOME", "/opt/dagster")
                    environment["PHLO_RUNTIME_UID"] = str(os.getuid())
                    environment["PHLO_RUNTIME_GID"] = str(os.getgid())
                elif isinstance(environment, list) and not any(
                    item.startswith("HOME=") for item in environment if isinstance(item, str)
                ):
                    environment.append("HOME=/opt/dagster")
                    environment.append(f"PHLO_RUNTIME_UID={os.getuid()}")
                    environment.append(f"PHLO_RUNTIME_GID={os.getgid()}")
            else:
                config.pop("user", None)

        if service.name == "phlo-api" and platform.system() == "Linux":
            # The API reads project secrets (.phlo/.env, .phlo/.env.local) from
            # the read-only project mount through pydantic settings. Those files
            # are host-owned with restrictive permissions (ADR 0047), so the
            # container must run as the generating host user to read them.
            config["user"] = f"{os.getuid()}:{os.getgid()}"

        # Dependencies
        if service.depends_on:
            depends_config: dict[str, dict[str, str]] = {}
            for dep in service.depends_on:
                dep_service = self.discovery.get_service(dep)
                if dep_service:
                    if dep.endswith("-setup"):
                        depends_config[dep] = {"condition": "service_completed_successfully"}
                    elif dep_service.compose.get("healthcheck"):
                        depends_config[dep] = {"condition": "service_healthy"}
                    else:
                        depends_config[dep] = {"condition": "service_started"}
            if depends_config:
                config["depends_on"] = depends_config

        self._apply_conditional_environment(config, compose, env_values or {})
        self._remove_windows_quoted_empty_environment_values(config, env_values or {})

        # Apply user overrides from phlo.yaml last, so they take precedence.
        self._apply_user_overrides(config, user_override)

        return config

    def _apply_conditional_environment(
        self,
        config: dict[str, Any],
        compose: dict[str, Any],
        env_values: Mapping[str, Any],
    ) -> None:
        """Add manifest-defined environment entries only when their trigger has a value."""
        conditional_environment = compose.get("conditional_environment", {})
        if not isinstance(conditional_environment, dict):
            return
        environment = config.get("environment")
        for trigger, entries in conditional_environment.items():
            trigger_name = str(trigger)
            trigger_value = self._normalise_optional_environment_value(
                env_values.get(trigger_name, "")
            )
            if not trigger_value or not isinstance(entries, dict):
                continue
            if environment is None:
                environment = {}
                config["environment"] = environment
            if isinstance(environment, dict):
                environment.update(entries)
            elif isinstance(environment, list):
                environment.extend(f"{key}={value}" for key, value in entries.items())

    @staticmethod
    def _normalise_optional_environment_value(value: Any) -> str:
        """Treat CMD's literal quoted-empty values as an unset optional value."""
        normalised = str(value).strip()
        return "" if normalised in {'""', "''"} else normalised

    @staticmethod
    def _is_windows_quoted_empty(value: Any) -> bool:
        """Return whether a value is CMD's literal quoted-empty representation."""
        return str(value).strip() in {'""', "''"}

    def _remove_windows_quoted_empty_environment_values(
        self, config: dict[str, Any], env_values: Mapping[str, Any]
    ) -> None:
        """Omit optional `${NAME:-}` entries set as `""` by Windows CMD.

        In CMD, `set NAME=""` stores the quote characters rather than an empty
        value. Docker Compose would otherwise pass those characters through to
        services, which makes optional integrations look partially configured.
        Only expressions with an explicitly empty fallback are removed; required
        values and non-empty defaults preserve their existing Compose behavior.
        """
        environment = config.get("environment")
        if isinstance(environment, dict):
            for key, value in list(environment.items()):
                variable = self._empty_default_variable(value)
                if (
                    variable
                    and variable in env_values
                    and self._is_windows_quoted_empty(env_values[variable])
                ):
                    del environment[key]
        elif isinstance(environment, list):
            config["environment"] = [
                entry
                for entry in environment
                if not (
                    isinstance(entry, str)
                    and "=" in entry
                    and (variable := self._empty_default_variable(entry.split("=", 1)[1]))
                    and variable in env_values
                    and self._is_windows_quoted_empty(env_values[variable])
                )
            ]

    @staticmethod
    def _empty_default_variable(value: Any) -> str | None:
        """Return the variable referenced by an exact `${NAME:-}` expression."""
        if not isinstance(value, str):
            return None
        match = _EMPTY_DEFAULT_ENVIRONMENT_EXPRESSION.fullmatch(value)
        return match.group(1) if match else None

    def _apply_user_overrides(
        self,
        config: dict[str, Any],
        user_override: dict[str, Any],
    ) -> None:
        """Apply user overrides from phlo.yaml services section.

        Override behavior:
        - ports: replaces package default
        - environment: merges (user values override package)
        - volumes: appends to package defaults
        - depends_on: replaces package default
        - command: replaces package default
        """
        if not user_override:
            return

        # `services init` reads raw project YAML, so validate it here as well as
        # in `phlo config validate` before it reaches Docker Compose.
        user_override = ServiceOverride.model_validate(user_override).model_dump(exclude_none=True)

        # Ports: replace
        if user_override.get("ports"):
            config["ports"] = user_override["ports"]

        # Environment: merge (user takes precedence)
        if user_override.get("environment"):
            config.setdefault("environment", {})
            if isinstance(config["environment"], list):
                # Convert list format to dict then merge
                config["environment"] = dict(
                    item.split("=", 1) for item in config["environment"] if "=" in item
                )
            config["environment"].update(user_override["environment"])

        # Volumes: append
        if user_override.get("volumes"):
            config.setdefault("volumes", [])
            config["volumes"].extend(user_override["volumes"])

        # Extra hosts: replace package defaults with explicit project routing.
        if "extra_hosts" in user_override:
            config["extra_hosts"] = list(user_override["extra_hosts"])

        # Depends on: replace
        if user_override.get("depends_on"):
            config["depends_on"] = {
                dep: {"condition": "service_started"} for dep in user_override["depends_on"]
            }

        # Command: replace
        if user_override.get("command"):
            config["command"] = user_override["command"]

        # Healthcheck: replace (for inline services)
        if user_override.get("healthcheck"):
            config["healthcheck"] = user_override["healthcheck"]

    def _apply_dev_overrides(
        self,
        config: dict[str, Any],
        service: ServiceDefinition,
        output_dir: Path,
    ) -> None:
        dev = service.dev

        # Dev build: replace image with build context
        if dev.get("build"):
            # Remove image if present (we're building from source now)
            if "image" in config:
                del config["image"]

            build_ctx = dev["build"].get("context", ".")
            # Resolve {source} placeholder
            if "{source}" in build_ctx and service.source_path:
                build_ctx = os.path.relpath(service.source_path, output_dir)

            config["build"] = {
                "context": build_ctx,
                "dockerfile": dev["build"].get("dockerfile", "Dockerfile"),
            }

        if dev.get("environment"):
            config.setdefault("environment", {})
            if isinstance(config["environment"], dict):
                config["environment"].update(dev["environment"])
        if dev.get("command"):
            config["command"] = dev["command"]
        if dev.get("entrypoint"):
            config["entrypoint"] = dev["entrypoint"]
        if dev.get("ports"):
            config["ports"] = dev["ports"]
        if dev.get("volumes"):
            config["volumes"] = [
                self._resolve_dev_volume(volume, service, output_dir) for volume in dev["volumes"]
            ]

    def _resolve_dev_volume(
        self,
        volume: str,
        service: ServiceDefinition,
        output_dir: Path,
    ) -> str:
        if not service.source_path:
            return volume
        source_path = str(os.path.relpath(service.source_path, output_dir))
        resolved = volume
        if "{source}" in resolved:
            resolved = resolved.replace("{source}", source_path)
        if "{source_path}" in resolved:
            resolved = resolved.replace("{source_path}", source_path)
        return resolved

    def generate_env(
        self,
        services: list[ServiceDefinition],
        env_overrides: dict[str, Any] | None = None,
    ) -> str:
        """Generate .env file content (non-secret defaults)."""
        return _generate_env(services, env_overrides=env_overrides)

    def generate_env_local(
        self,
        services: list[ServiceDefinition],
        env_overrides: dict[str, Any] | None = None,
        existing_values: dict[str, str] | None = None,
    ) -> str:
        """Generate .env.local file content (secrets and local overrides)."""
        return _generate_env_local(
            services, env_overrides=env_overrides, existing_values=existing_values
        )

    def copy_service_files(
        self,
        services: list[ServiceDefinition],
        output_dir: Path,
    ) -> list[str]:
        """Copy each service's additional files into the .phlo output
        directory, returning the copied paths relative to it.
        """
        copied: list[str] = []

        for service in services:
            if not service.files or not service.source_path:
                continue

            for file_spec in service.files:
                source = service.source_path / file_spec["source"]
                dest = output_dir / file_spec["dest"]

                if not source.exists():
                    logger.warning(
                        "compose_service_file_source_missing",
                        service_name=service.name,
                        source=str(source),
                        destination=str(dest),
                    )
                    continue

                # Create parent directories
                dest.parent.mkdir(parents=True, exist_ok=True)

                # Copy file or directory
                if source.is_dir():
                    if dest.exists():
                        shutil.rmtree(dest)
                    shutil.copytree(source, dest)
                else:
                    shutil.copy2(source, dest)

                copied.append(str(dest.relative_to(output_dir)))

        return copied

    def generate_gitignore(self, services: list[ServiceDefinition]) -> str:
        """Generate .gitignore content for .phlo directory."""
        entries: list[str] = [
            "# Phlo infrastructure files",
            ".env",
            ".env.local",
            "volumes/",
        ]

        extra_entries: list[str] = []
        staged_lock_entries = [
            "# Staged uv lock metadata (source of truth lives at the project root)",
            *UV_LOCK_METADATA_FILES,
        ]

        for service in services:
            for entry in service.gitignore:
                if entry not in extra_entries:
                    extra_entries.append(entry)

        if extra_entries:
            entries.append("")
            entries.append("# Service runtime data")
            entries.extend(extra_entries)

        entries.append("")
        entries.extend(staged_lock_entries)

        return "\n".join(entries) + "\n"
