"""Registers the Hasura service plugin.

The plugin class is generated by ``service_plugin_class`` and carries
identity metadata only.

Loaded through the phlo plugin entry-point mechanism at startup rather than imported directly.
"""

from __future__ import annotations

from phlo.plugins import service_plugin_class


HasuraServicePlugin = service_plugin_class(
    "HasuraServicePlugin",
    name="hasura",
    version="0.1.0",
    description="GraphQL API engine with real-time subscriptions",
    author="Phlo Team",
    tags=["api", "graphql"],
)
